[package]
name = "wincwifi"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "0.3.2" }
log = {version="0.4.17", default-features = false, optional=true }

# this version lacks read() from mutable byte slices
# genio =  { version = "0.2.1" , default-features = false }
genio =  { git = "https://github.com/Kixunil/genio.git", rev="32aa022" , default-features = false }

arrayvec =  { version = "0.7.2", default-features = false }
# thiserror # https://fettblog.eu/rust-enums-wrapping-errors/

crc-any = { version = "2.4.3", default-features = false }

no-std-net = "0.6.0"

embedded-nal = "0.8.0"

[dependencies.simple_logger]
default-features = false
version="4.0.0"
optional = true

[dev-dependencies]
test-log = "0.2.11"

[dev-dependencies.void]
version = "1"
default-features = false
features = ["std"]
# optional = true

[features]
std=["genio/std", "dep:log", "dep:simple_logger"]
default = ["std"]
